# Generated by Django 5.1.3 on 2025-02-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(blank=True, choices=[('p', 'Преподаватель'), ('s', 'Студент'), ('a', 'Администратор')], default='s', max_length=2)),
                ('status', models.CharField(choices=[('ac', 'Активный'), ('in', 'Неактивный'), ('pd', 'В ожидании')], default='in', max_length=2)),
                ('image', models.ImageField(upload_to='users/')),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
