# Generated by Django 5.1.3 on 2025-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ac', 'Активный'), ('in', 'Неактивный'), ('pd', 'В ожидании')], default='in', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('p', 'Преподаватель'), ('s', 'Студент'), ('a', 'Администратор')], default='s', max_length=2),
        ),
    ]
