# Generated by Django 5.1.3 on 2025-02-17 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_status_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
